export const SET_TEAM_DATA_DOWNLOAD_STARTED = 'SET_TEAM_DATA_DOWNLOAD_STARTED';
export const SET_TEAM_DATA_DOWNLOAD_DONE = 'SET_TEAM_DATA_DOWNLOAD_DONE';
export const SET_TEAM_DATA = 'SET_TEAM_DATA';
export const SET_PROJECT_DATA_DOWNLOAD_STARTED = 'SET_PROJECT_DATA_DOWNLOAD_STARTED';
export const SET_PROJECT_DATA_DOWNLOAD_DONE = 'SET_PROJECT_DATA_DOWNLOAD_DONE';
export const SET_PROJECT_DATA = 'SET_PROJECT_DATA';
export const CLEAR_DATA = 'CLEAR_DATA';