export const SET_ALL_TEAMS_DATA = 'SET_ALL_TEAMS_DATA';
export const CLEAR_ALL_TEAMS_DATA = 'CLEAR_ALL_TEAMS_DATA';
export const SET_SELECTED_TEAM = 'SET_SELECTED_TEAM';
export const CLEAR_SELECTED_TEAM = 'CLEAR_SELECTED_TEAM'