export const SET_USER_DATA = 'SET_USER_DATA';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const SET_USER_DATA_DONE = 'SET_USER_DATA_DONE';
export const SET_OPEN_USER = 'SET_OPEN_USER';
export const CLEAR_OPEN_USER = 'CLEAR_OPEN_USER';