export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT';
export const CLEAR_SELECTED_PROJECT = "CLEAR_SELECTED_PROJECT";
export const SET_PROJECT_MESSAGES = "SET_PROJECT_MESSAGES";
export const CLEAR_PROJECT_MESSAGES = "CLEAR_PROJECT_MESSAGES";
export const SET_PROJECT_FILES = "SET_PROJECT_FILES";
export const CLEAR_PROJECT_FILES = "CLEAR_PROJECT_FILES";