export const SET_ADMIN_DATA = 'SET_ADMIN_DATA';
export const CLEAR_ADMIN_DATA = 'CLEAR_DATA';
export const UPDATE_ADMIN_TEAM_MEMBERS = 'UPDATE_ADMIN_TEAM_MEMBERS';
export const REMOVE_USER_FROM_TEAM_ADMIN = 'REMOVE_USER_FROM_TEAM_ADMIN';