export const SET_ADMIN_DATA = 'SET_ADMIN_DATA';
export const CLEAR_ADMIN_DATA = 'CLEAR_DATA';
export const UPDATE_ADMIN_TEAM_MEMBERS = 'UPDATE_ADMIN_TEAM_MEMBERS';
export const REMOVE_USER_FROM_TEAM_ADMIN = 'REMOVE_USER_FROM_TEAM_ADMIN';
export const UPDATE_TEAM_PROJECT_ADMIN = 'UPDATE_TEAM_PROJECT_ADMIN';
export const SET_ADMIN_DATA_STATUS = 'SET_ADMIN_DATA_STATUS';
export const SET_NEW_TEAM_CREATED = 'SET_NEW_TEAM_CREATED';
export const ADMIN_REMOVE_PROJECT_FROM_TEAM = 'ADMIN_REMOVE_PROJECT_FROM_TEAM';